### ISSUE TITLE
Add ability to show categories/products instead of just hide

### ISSUE THREAD

**Issue by roykho** [roykho/woocommerce-geolocation-based-products#1]
- [x] - Add drag and drop sorting of the rules ( Ascending - meaning rules towards the bottom will supercede the rules on top )
- [x] - Add dropdown select option for hide/show
- [x] - Make country, region, city field to accept `*` for all instead of disable.  So if left blank ( meaning \* ), will either show/hide for all country, region or city respectively.
- [x] - Add frontend logic to show/hide products and categories

**Comment by patrickgilmour** [comment]
+1 for this idea!

**Comment by roykho** [comment]
This feature is complete.
