### ISSUE TITLE
How to enable this in Dokan

### ISSUE THREAD

**Issue by Krupaly2k-zz** [roykho/woocommerce-geolocation-based-products#18]
Hi,

I am using Dokan extension for multivendor. How can i use this plugin from seller side. So, seller can set specific country where they want to display that product.

Thanks in advance!

Thanks,
Krupal

**Comment by roykho** [comment]
Hello,

Sorry this is not a question I can answer for you as I don't know how Dokan works. But it sounds like you would need some custom integration for this.
