### ISSUE TITLE
showing a tag in 2 locations hides it for all

### ISSUE THREAD

**Issue by WolfMachina** [roykho/woocommerce-geolocation-based-products#19]
I have a universal rule hiding one tag as it's only needed for two locations, this tag then shows fine for one location but on adding a second showing the same tag it hides the products again. is this a bug or am I doing something wrong?

**Comment by roykho** [comment]
Please post support related questions here https://wordpress.org/support/plugin/woocommerce-geolocation-based-products

**Comment by WolfMachina** [comment]
sure thing, thanks very much
