### ISSUE TITLE
Commercial usage of IP-API.com

### ISSUE THREAD

**Issue by vladc** [roykho/woocommerce-geolocation-based-products#6]
We do not allow commercial usage of our free API, ip-api.com. Please discontinue your usage of it in your code.

Alternative APIs: https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-geolocation.php#L40-L42

**Comment by roykho** [comment]
HI @vladc 

Sorry can you please explain?  I have read your terms of use prior to using and it states for non commercial use.  This plugin is 100% free and not sold commercially or privately.  Or am I misunderstanding the terms?  If so, I will be happy to oblige.  

Thanks!

**Comment by vladc** [comment]
@roykho your plugin may be 100% free and not sold commercially or privately, but it's intended for commercial use, as per your description: "A WooCommerce plugin/extension that adds ability for your **store** to hide products based on visitors geolocation taken from IP address."
Hence, your users are using consuming the API for business purposes.

**Comment by roykho** [comment]
@vladc 

Please have a read here https://wiki.creativecommons.org/wiki/NonCommercial_interpretation

It states I am following the rights of use for a "NonCommercial" terms.

However I will be happy to remove this per your request.  Sorry for any troubles.

**Comment by roykho** [comment]
Closed via https://github.com/roykho/woocommerce-geolocation-based-products/commit/3b1ff42dcb6774dd148546e7dec633847d7ef44e
