### ISSUE TITLE
Does the plugin work with varaible products?

### ISSUE THREAD

**Issue by francoisw** [roykho/woocommerce-geolocation-based-products#7]
Hi there,

Does this plugin work with variable products. eg. a physical & e-book where the e-book is available for sale everywhere and the physical book is available to purchase in one country only. All other countries are blocked. 
It could work to create separate products for e-book and physical but the other solution will be more elegant. Any help will be greatly appreciated.

Kind regards
Francois Wessels

**Comment by roykho** [comment]
In the future please post support questions here https://wordpress.org/plugins/woocommerce-geolocation-based-products/ as this is for plugin contribution such as bug fixes..etc.

But to answer your question, it only works for the base/parent product itself and cannot differentiate by variation.
